CREATE TABLE FLIGHT_BOOKINGS (
    BOOKING_ID INT AUTO_INCREMENT PRIMARY KEY,
    FLIGHT_NUMBER VARCHAR(10),
    PASSENGER_DETAILS JSON,
    BOOKING_DATE DATE
);

INSERT INTO FLIGHT_BOOKINGS (FLIGHT_NUMBER, PASSENGER_DETAILS, BOOKING_DATE) VALUES
('AI101', '{"name": "John Doe", "age": 32, "seat": "12A"}', '2024-12-07'),
('AI202', '{"name": "Jane Smith", "age": 28, "seat": "15B"}', '2024-12-10'),
('AI303', '{"name": "Sam Wilson", "age": 45, "seat": "18C"}', '2024-12-13');

SELECT 
    FLIGHT_NUMBER,
    JSON_EXTRACT(PASSENGER_DETAILS, '$.name') AS NAME,
    JSON_EXTRACT(PASSENGER_DETAILS, '$.seat') AS SEAT
FROM FLIGHT_BOOKINGS
WHERE BOOKING_DATE >= CURDATE() - INTERVAL 7 DAY;
